---
name: Improvement
description: Suggest an improvement or new feature.
title: '💡 '
labels: ['enhancement', 'triage']
projects: ['DelineaXPM/delinea-mcp']
assignees:
  - '@DelineaXPM/mcp-contributors'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an improvement!
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe what you're trying to accomplish.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: I'd like to be able to...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've thought about...
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Critical for my use case
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/DelineaXPM/delinea-mcp?tab=coc-ov-file#readme){:target="_blank"}.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
